// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChromaMode } from "./ChromaMode";
import type { ClaudeConfig } from "./ClaudeConfig";
import type { CloneAccountRedacted } from "./CloneAccountRedacted";
import type { CloneGroup } from "./CloneGroup";
import type { EnvPreset } from "./EnvPreset";
import type { LinearKeysSet } from "./LinearKeysSet";
import type { ListenConfig } from "./ListenConfig";
import type { MonitorSpec } from "./MonitorSpec";
import type { TemplateConfig } from "./TemplateConfig";

/**
 * The shape `GET /api/config` returns: same structure as [`AppConfig`] but with
 * every secret replaced by a boolean "is set". Powers the Settings UI.
 */
export type AppConfigRedacted = { listen: ListenConfig, agentPort: number, dataDir: string, staticDir: string, monitors: Array<MonitorSpec>, proxmoxSshSet: boolean, proxmoxHostnamePrefix: string, linearKeysSet: LinearKeysSet, claude: ClaudeConfig, cloneAccounts: Array<CloneAccountRedacted>, cloneGroups: Array<CloneGroup>, template: TemplateConfig, envPresets: Array<EnvPreset>, chroma: ChromaMode, detectorInferenceUrl: string, };
