// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChromaMode } from "./ChromaMode";
import type { ClaudeConfig } from "./ClaudeConfig";
import type { CloneGroup } from "./CloneGroup";
import type { DockerConfig } from "./DockerConfig";
import type { ListenConfig } from "./ListenConfig";
import type { MonitorSpec } from "./MonitorSpec";
import type { PresetRedacted } from "./PresetRedacted";

/**
 * The shape `GET /api/config` returns: same structure as [`AppConfig`] but with
 * every secret replaced by a boolean "is set". Powers the Settings UI.
 */
export type AppConfigRedacted = { listen: ListenConfig, agentPort: number, dataDir: string, staticDir: string, cloneSocket: string, setupComplete: boolean, monitors: Array<MonitorSpec>, docker: DockerConfig, claude: ClaudeConfig, cloneGroups: Array<CloneGroup>, presets: Array<PresetRedacted>, chroma: ChromaMode, detectorInferenceUrl: string, };
