// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClaudeConfig = { 
/**
 * Usage poll interval (seconds, floored at 15).
 */
pollSecs: bigint, 
/**
 * Account email pinned to the top of the usage list.
 */
pinnedEmail: string | null, 
/**
 * Hot-swap a clone to another account when its usage is exhausted.
 */
autoSwapOnExhaustion: boolean, };
