// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeSpend } from "./ClaudeSpend";
import type { ClaudeUsageWindow } from "./ClaudeUsageWindow";
import type { Provider } from "./Provider";

/**
 * A non-secret per-account usage view (tokens never enter this struct).
 */
export type ClaudeUsage = { 
/**
 * Stable id: claude `${email}|${orgUuid}`, codex `codex:<id>`.
 */
id: string, email: string, provider: Provider | null, active: boolean, 
/**
 * Whether the account can run a clone: true for every imported account of either
 * provider (the server owns each account's token lifecycle).
 */
assignable: boolean | null, error: string | null, stale: boolean | null, lastUpdated: bigint, fiveHour: ClaudeUsageWindow | null, sevenDay: ClaudeUsageWindow | null, spend: ClaudeSpend | null, };
