// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named pool of clone accounts (by email). A clone bound to a group has its
 * account rotated among the group's members every cycle (by 5h usage). Carries no
 * secrets — just a name + member emails — so it's TS-exported and shown verbatim in
 * the redacted config.
 */
export type CloneGroup = { name: string, accounts: Array<string>, };
