// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named pool of clone accounts (by email). A clone bound to a group sticks to its
 * account until that account exceeds the 5h usage cap (or leaves the group), then
 * moves to the group's least-loaded / least-used member — sticky, because an account
 * switch cold-starts the clone's prompt cache. Carries no secrets — just a name +
 * member emails — so it's TS-exported and shown verbatim in the redacted config.
 */
export type CloneGroup = { name: string, accounts: Array<string>, };
