// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexConfig = { 
/**
 * Usage poll interval (seconds, floored at 15 by the poller).
 */
pollSecs: bigint, 
/**
 * Account email pinned to the top of the usage list.
 */
pinnedEmail: string | null, 
/**
 * Hot-swap a clone to another account when its usage is exhausted.
 */
autoSwapOnExhaustion: boolean, 
/**
 * Poll the ChatGPT usage endpoint. When false, the poller still refreshes + pushes
 * tokens and publishes base views (with an explanatory `error`), but skips the usage
 * fetch — an escape hatch if the unofficial `/wham/usage` shape drifts.
 */
usagePolling: boolean, };
