// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConfigRedacted } from "./AppConfigRedacted";

/**
 * Response body for `PUT /api/config`: the redacted config after the merge, plus
 * whether the change touched a restart-required setting (the UI surfaces a restart
 * prompt when `restartRequired` is true).
 */
export type ConfigPutResponse = { config: AppConfigRedacted, restartRequired: boolean, };
