// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeUsage } from "./ClaudeUsage";
import type { Host } from "./Host";
import type { MonitorSpec } from "./MonitorSpec";
import type { Operation } from "./Operation";

/**
 * The top-level state broadcast over `/events` and persisted to `state.json`.
 */
export type ControlState = { 
/**
 * Id of the host that should be displayed. May be absent or point at a host
 * not in the list; consumers must tolerate both.
 */
selected: string | null, monitors: Array<MonitorSpec>, 
/**
 * Name of the active layout preset (mirrored from config so the sidebar switcher
 * updates live over `/events`). Empty when no presets exist.
 */
activeLayout: string, 
/**
 * Names of all layout presets, in config order — the sidebar's segmented buttons.
 */
layoutPresetNames: Array<string>, hosts: Array<Host>, operations: Array<Operation>, 
/**
 * Per-Claude-account usage view (no tokens).
 */
claudeAccounts: Array<ClaudeUsage>, };
