// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live per-container resource usage, sampled by the monitor poller each tick and pushed
 * to the frontend as a named `stats` SSE event carrying a `{ hostId: ContainerStats }`
 * map. Deliberately NOT a field of [`ControlState`] / [`Host`]: it changes every tick, so
 * routing it through the state store would rewrite `state.json` every few seconds (every
 * `ControlState` mutation persists — see the control-server's `state.rs`). It rides the
 * same `/events` stream on a separate SSE-only bus instead.
 */
export type ContainerStats = { 
/**
 * CPU use as a percentage of ONE core (100 == a single fully-used core; a container
 * busy across several cores reads > 100). The frontend divides by 100 to display
 * "cores".
 */
cpuPct: number, 
/**
 * Resident memory in bytes, docker-CLI semantics (`usage` minus reclaimable
 * `inactive_file` page cache).
 */
memUsed: bigint, 
/**
 * Memory limit in bytes; 0 when the daemon reports none.
 */
memLimit: bigint,
/**
 * Total Docker daemon disk usage in bytes. This is daemon-wide, not per-container;
 * the monitor repeats it on each live stats sample so the frontend can show one
 * sidebar total without routing volatile data through `ControlState`.
 */
dockerDiskUsed: bigint, };
