// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Docker backend settings for the clone fleet. No secrets — the local daemon is
 * reached over the unix socket, so (unlike the retired Proxmox SSH target) there is
 * nothing to redact; the whole struct passes through into [`AppConfigRedacted`].
 */
export type DockerConfig = { 
/**
 * Docker daemon unix socket the control-server drives clones through, e.g.
 * `/var/run/docker.sock`. **Restart-required**: the bollard client is built at
 * startup.
 */
socket: string, 
/**
 * CIDR for the user-defined `rmng` bridge network (`.1` gateway, `.2` control-server,
 * `.10+` clone pool). **One-time**: baked into the network + every clone's static IP
 * at first-run setup (validated `/16`–`/24` at config merge).
 */
subnet: string, 
/**
 * Prefix for derived clone hostnames/names, e.g. `pega-` → `pega-dev-123`. Sanitized
 * to DNS-label-safe chars at use; blank in the UI keeps the stored value. Immediate
 * (carried from the retired `proxmox.hostname_prefix`).
 */
hostnamePrefix: string, 
/**
 * CPU limit per clone (`nano_cpus` = `clone_cpus * 1e9`), matching LXC parity.
 */
cloneCpus: number, 
/**
 * Memory limit per clone in MiB (+8 GiB swap), matching LXC parity.
 */
cloneMemoryMb: number, 
/**
 * Registry reference the setup wizard pulls the clone template from, then retags
 * locally to `rmng/template:<name>`. Short form (`repo:tag`) so it matches what the
 * pulled image's RepoTags will contain. Immediate-apply (read fresh per pull); no
 * secret (public image over the local daemon), so it passes through the redacted view.
 */
templateReference: string, };
