// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the setup wizard's environment preflight (`GET /api/setup/env`): a named
 * check (Docker socket reachable, kernel features, etc.) with its pass/fail verdict.
 */
export type EnvCheckRow = { 
/**
 * Stable machine id for the check (e.g. `dockerSocket`).
 */
id: string, 
/**
 * Human-readable label shown in the wizard.
 */
label: string, 
/**
 * Whether the check passed.
 */
ok: boolean, 
/**
 * Detail / diagnostic line shown under the label (empty when nothing to add).
 */
detail: string, 
/**
 * Whether a failure blocks setup (vs. an advisory warning).
 */
required: boolean, };
