// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForwardState } from "./ForwardState";

/**
 * One rule's runtime status inside the `forwards` SSE event (payload:
 * `Record<hostId, ForwardRuntime[]>`).
 */
export type ForwardRuntime = { id: string, state: ForwardState, error: string | null, activeConns: number, };
