// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live state of a forward rule. `Offline` is server-derived (no viewer connected);
 * the viewer only ever reports `Listening`/`Error`.
 */
export type ForwardState = "listening" | "error" | "offline";
