// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReport } from "./AgentReport";
import type { MonitorState } from "./MonitorState";

export type Host = { 
/**
 * Stable id; equals the Docker container name for cloneable hosts.
 */
id: string, 
/**
 * RDP/media server hostname or IP.
 */
host: string, 
/**
 * Port (defaults to 3389 for the legacy RDP path).
 */
port: number, username: string, password: string, domain: string | null, gdm_username: string | null, gdm_password: string | null, 
/**
 * Docker container id (full 64-hex) of the managed clone backing this host; the
 * container *name* equals the host id for `docker ps` readability. `Some` marks a
 * managed clone; `None` is a plain unmanaged row (deletable in the UI). Old
 * `state.json` rows carrying the legacy `ctid` load as `None` — serde drops the
 * stale key.
 */
container: string | null, source: string | null, claudeAccountEmail: string | null, 
/**
 * Name of the Claude group this clone is balanced within (sticky — it moves only
 * when its account exhausts); `None` when bound to a single fixed account. When
 * set, `claude_account_email` holds the current pick.
 */
claudeGroup: string | null, 
/**
 * The operator's Claude *selection* verbatim: `"auto"`, `"none"`, `"group:<name>"`,
 * or an account email. Distinguishes an auto-managed clone (server picks the best
 * account and may hot-swap it) from one pinned to a fixed account or opted out of
 * a token entirely — `claude_account_email` alone can't tell these apart. `None` on
 * hosts created before this field / when no Claude account is configured.
 */
claudeSelection: string | null, 
/**
 * Lowercase Linear workspace name / ticket prefix (e.g. `"we"`). An open
 * string: the workspace set is config (Settings → Linear API keys), not an enum.
 */
linearWorkspace: string | null, linearTicket: string | null, linearTicketUrl: string | null, linearBranch: string | null, displayName: string | null, linearLabel: string | null, agentReport: AgentReport | null, stateNote: string | null, monitorState: MonitorState | null, 
/**
 * True when this clone fell out of `working` (→ idle/offline) since the
 * operator last viewed it — drives the sidebar "unread" dot. Set by the
 * monitor poller on that transition, cleared when the clone is activated.
 */
unread: boolean, };
