// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A clone-source image (labeled `rmng.image=1`) as shown to the browser
 * (`GET /api/images`). Images replace the retired host-id templates: any clone can be
 * committed to one, and clone creation picks from these.
 */
export type ImageInfo = { 
/**
 * Full image id (`sha256:…`).
 */
id: string, 
/**
 * Repo tag reference, e.g. `rmng/template:my-base`.
 */
reference: string, sizeBytes: bigint, 
/**
 * ISO timestamp the image was created.
 */
createdAt: string, 
/**
 * True for the wizard-built base image (`rmng.base=1`).
 */
base: boolean, 
/**
 * Lineage: the reference this image was committed from (`rmng.created-from`), if any.
 */
createdFrom: string | null, 
/**
 * Host ids of live clones currently running on this image.
 */
inUseBy: Array<string>, };
