// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorSpec } from "./MonitorSpec";

/**
 * A named monitor-layout preset: a full arrangement the operator can switch to.
 * Distinct from clone-provisioning `Preset` (env/Linear) — this is display geometry only.
 */
export type LayoutPreset = { name: string, monitors: Array<MonitorSpec>, };
