// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The four listen ports (see README: 1 video, 2 web, 3 per-clone MCP, 4 global MCP).
 */
export type ListenConfig = { web: number, video: number, cloneMcp: number, globalMcp: number, 
/**
 * The clone-daemon's in-clone HTTP MCP port. The fleet MCP proxies desktop/window
 * tools to `http://{clone-ip}:{daemon_mcp}`; each clone-daemon listens here (set via
 * `RMNG_DAEMON_MCP_PORT`). Same value for every clone.
 */
daemonMcp: number, 
/**
 * The control-server's port-forward data plane. The viewer opens one TCP
 * connection here per accepted local socket; the server splices to the clone.
 * Restart-required (bound at startup).
 */
forward: number, };
