// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The control-server listen ports: video, web, per-clone MCP, the in-clone daemon MCP,
 * and the forward data plane (see README).
 */
export type ListenConfig = { web: number, video: number, cloneMcp: number, 
/**
 * The clone-daemon's in-clone HTTP MCP port. The control-server proxies desktop/window
 * tools (`POST /api/hosts/:id/mcp`) to `http://{clone}:{daemon_mcp}`; each clone-daemon
 * listens here (set via `RMNG_DAEMON_MCP_PORT`). Same value for every clone.
 */
daemonMcp: number, 
/**
 * The control-server's port-forward data plane. The viewer opens one TCP
 * connection here per accepted local socket; the server splices to the clone.
 * Restart-required (bound at startup).
 */
forward: number, 
/**
 * The bastion `sshd` port (jump host into clones). Restart-required (bound at startup).
 */
bastion: number, };
