// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKind } from "./OperationKind";
import type { OperationStatus } from "./OperationStatus";

export type Operation = { id: string, kind: OperationKind, 
/**
 * Host id being created (clone) or removed (delete).
 */
target: string, source: string | null, status: OperationStatus, 
/**
 * Current step key (maps to a coarse percentage in the UI).
 */
step: string, 
/**
 * 0–100.
 */
pct: number, message: string, 
/**
 * Rolling log lines for the operation.
 */
log: Array<string>, startedAt: bigint, finishedAt: bigint | null, };
