// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One local-forward rule: a TCP port inside this clone (`remote_port`) exposed at
 * `127.0.0.1:<local_port>` on the machine running the native viewer. Persisted in
 * `state.json`; the viewer runs the listener. `id` is derived server-side as
 * `f{local_port}` (local ports are globally unique across all hosts' rules).
 */
export type PortForward = { id: string, remotePort: number, localPort: number, enabled: boolean, label: string | null, };
