// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVar } from "./EnvVar";

/**
 * A preset as shown to the browser: everything but the Linear key, which is
 * replaced by a "is set" flag (write-only secret).
 */
export type PresetRedacted = { name: string, labels: Array<string>, linearKeySet: boolean, vars: Array<EnvVar>, };
