// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvCheckRow } from "./EnvCheckRow";

/**
 * Response body for `GET /api/setup/env`: the environment preflight rows.
 */
export type SetupEnv = { rows: Array<EnvCheckRow>, };
