// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSH access settings. The control-server always runs a jump-only bastion `sshd`
 * (no enable/disable toggle — same as the SMB share); these keys are installed on the
 * bastion AND every clone. An empty `authorized_keys` means no keys get pasted in.
 * Public keys are NOT secret — the whole struct passes through [`AppConfigRedacted`].
 */
export type SshConfig = { 
/**
 * Authorized SSH public keys, one full line each (`ssh-ed25519 AAAA… comment`).
 */
authorizedKeys: Array<string>, 
/**
 * Public host/IP the copied command's `-J` jump targets. Empty ⇒ the UI infers it
 * from the address it's already served on. Not secret.
 */
publicHost: string, };
