// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Version + update-available status for the control-server itself, served by
 * `GET /api/server/version`. `current_*` come from the running image's OCI labels /
 * RepoDigest; `remote_digest` from a registry manifest query (no pull). `available` is
 * true when a remote digest was fetched and differs from the running one. `error` carries
 * a non-fatal detail (e.g. registry unreachable) so the UI can show "couldn't check".
 */
export type UpdateStatus = { currentRevision: string | null, currentCreated: string | null, currentDigest: string | null, remoteDigest: string | null, available: boolean, reference: string, error: string | null, };
